version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: lms_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: lms_user
      POSTGRES_PASSWORD: lms_password
      POSTGRES_DB: lms_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U lms_user -d lms_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  server:
    build:
      context: ./server
    container_name: lms_server
    ports:
      - "3001:3000"
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    env_file:
      - ./server/.env

volumes:
  postgres_data: 