version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: lms_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: lms_user
      POSTGRES_PASSWORD: lms_password
      POSTGRES_DB: lms_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  server:
    build:
      context: ./server
    container_name: lms_server
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    restart: unless-stopped
    env_file:
      - ./server/.env

volumes:
  postgres_data: 